#!/bin/bash

#!/bin/sh
IP=$(/bin/hostname -I | awk '{print $1}')
if [ "$IP" != "" ] ; then
  grep -q $IP /etc/resolv.conf
  if [ "$?" != "0" ] ; then
    sed -i "/nameserver.* # coredns/d" /etc/resolv.conf
    sed -i "0,/nameserver/s/nameserver/nameserver $IP #coredns\n&/" /etc/resolv.conf
  fi
fi
